### ISSUE TITLE
Debug using developer tool

### ISSUE THREAD

**Issue by anita00001** [zunairkhan811/Zunair-Desktop-Responsive-Portfolio#12]
Your project looks great! You have put an enormous effort into achieving this. However, if you could improve a few things, it would be bug-free.

index.js : In line 153, you have selected a class that never exist.
![image](https://user-images.githubusercontent.com/24216198/216755478-70d964f7-ef3c-4ece-b977-3fd4e9295356.png)
Rather, the target has an id. 
![image](https://user-images.githubusercontent.com/24216198/216755548-ab23c621-bef0-486f-91e7-2b178fbbd93c.png)

So, instead of dot (.), you can use hash (#).

Also, on the mobile menu, 

- On selecting menu-item **About** it is not scrolling to the respective section on the page.
- - On selecting menu-item **Contact** it is not scrolling to the respective section on the page.

**Comment by zunairkhan811** [comment]
Thanks for your suggestion. The bug has been removed. 😉
