### ISSUE TITLE
Peer-peer code review

### ISSUE THREAD

**Issue by vanina123** [zunairkhan811/Zunair-Desktop-Responsive-Portfolio#13]
Nice work implementing the Portfolio website, everything is working so well and very attractive user interface✅👍.
We suggest redirecting the email icon to your email address.
cheers and happy coding...
![StandingOvationGIF](https://user-images.githubusercontent.com/71019051/231086467-ba5a8a44-216c-45c6-b663-91e711ad9ffd.gif)

**Comment by zunairkhan811** [comment]
Hi! Thanks for your suggestion. Your suggestion has been implemented 😉 

https://github.com/zunairkhan811/Zunair-Desktop-Responsive-Portfolio/blob/1d5e9931545758914feeda6b22ea50d188002189/index.html#L40
