### ISSUE TITLE
Regarding Mobile Menu project

### ISSUE THREAD

**Issue by dheerajsachdeva** [zunairkhan811/Zunair-Desktop-Responsive-Portfolio#7]
Hello,

Good job done. No Linter errors and HTML and CSS Code is clean.

- Great commits!
- Consider adding a smoother transition time for the menú
- Review if a for loop or 'is active' class can be implemented in the JS section

Thanks
Morning Session Team

**Comment by zunairkhan811** [comment]
Thanks for your suggestion really appreciate that. Changes have been made to the code.
